### ISSUE TITLE
Ability to add custom function for version compare

### ISSUE THREAD

**Issue by Arti3DPlayer** [dsheiko/nw-autoupdater#11]
I have a version that looks like: `"version": "0.256.00",` and your lib says me that i have incorrect version... It will be cool to improve  compare:

http://stackoverflow.com/a/6832721/11236

or add ability to use custom function

**Comment by dsheiko** [comment]
A bit unusual request. I'm using official npm module SEMVER https://github.com/npm/node-semver
```
semver.gt( remoteManifest.version, this.manifest.version )
```
It's kinda de facto standard. But ok, why not. I'm going to think about

**Comment by Arti3DPlayer** [comment]
I don't know why all use `semver` library if it is better just use own function on 30 lines and remove dependency :)

**Comment by dsheiko** [comment]
Because it's a standard with clear specification, meaning I can rely on it. I guess we can close this one.
