### ISSUE TITLE
Dont't understand how to write VERBOSE .

### ISSUE THREAD

**Issue by tangyue0924** [dsheiko/nw-autoupdater#12]
Thanks for reading!
`const updater = new AutoUpdater( require( "../package.json" ), {strategy: 'ScriptSwap', verbose: true});`
Is that right?
If right, where to write the following script?How to declare variable of this script?

I just want to replace the `index.html` and `static` folder.

THX again!

**Comment by tangyue0924** [comment]
@dsheiko

**Comment by dsheiko** [comment]
Heyy @tangyue0924 
`options.verbose` is meant for detailed logs.

> By default nw.App.dataPath + "/nw-autoupdater.log": Windows: %LOCALAPPDATA%/<project_name>; Linux: ~/.config/<project_name>; OSX: ~/Library/Application Support/<project_name>

You most likely mean `options.swapScript`:

```
 const updater = new AutoUpdater( require( "./package.json" ), {
          strategy: "ScriptSwap",
          swapScript: `
rsync -a\${VERBOSE} --delete \${APP_PATH}/. \${BAK_PATH}/
rsync -a\${VERBOSE} \${UPDATE_PATH}/. \${APP_PATH}/static
`
      });
```

**Comment by tangyue0924** [comment]
@dsheiko Thanks, big bro! Your projects help me so much!

**Comment by dsheiko** [comment]
So I close it for now. If any questions you can either reopen the issue or reach me via https://gitter.im/dsheiko/nw-autoupdater
