### ISSUE TITLE
Doesn't restart after update, but updates without problems

### ISSUE THREAD

**Issue by denigada** [dsheiko/nw-autoupdater#30]
I am using the swap() function and then the restart() function to replace the original app with the updated version and start it up.
` const updateFile = await updater.download(rManifest);
            await updater.unpack(updateFile);
            await updater.swap();
            alert(`The application will automatically restart to finish installing the update`);
            await updater.restart();`

If I close the app and open it back, it is perfectly updated, but it won't automatically restart the app after the update.

**Comment by dsheiko** [comment]
If you do it on Mac, you have to first sign up your app, otherwise it won't restart automatically.
