### ISSUE TITLE
Beta 1.1.0 macos errors.

### ISSUE THREAD

**Issue by cry0m1** [dsheiko/nw-autoupdater#5]
Unsuccess test. I did not do complete test/debug due to insufficient time.

Again, `swap.sh` creates backup of parent folder for `application.app`, imagine it is in standard macos `/Applications` folder, backup 30GB.

First run in mac:
```
index.html:67 Error: spawn EACCES
    at exports._errnoException (util.js:1050:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at exports.spawn (child_process.js:378:9)
    at Promise (/Users/%USER%/%APP%/node_modules/nw-autoupdater/Lib/utils.js:46:15)
    at Promise (<anonymous>)
    at launch (/Users/%USER%/%APP%/node_modules/nw-autoupdater/Lib/utils.js:43:11)
    at AutoUpdater.restartToSwap (/Users/%USER%/%APP%/node_modules/nw-autoupdater/Lib/Strategy/ScriptSwap.js:15:11)
```

Just add `fs.chmodSync(scriptPath, '0755');` to [/Lib/Swap/Mac.js](https://github.com/dsheiko/nw-autoupdater/blob/release-1.1.0/Lib/Swap/Mac.js)

If something went wrong, application re-run causes:
```
index.html:67 Error: Cannot unpack .tar.gz package /var/folders/64/sthbgckj4xgbsd_t11pfxpjc0000gn/T/mac-x64.tar.gz
    at AutoUpdater.unpack (/Users/%USER%/%APP%/node_modules/nw-autoupdater/index.js:126:19)
    at <anonymous>
```

Finally swap.sh created folder back of mac os app, but did not copy new app to orig place and did not start it as well.

**Comment by dsheiko** [comment]
Oh thank you. Gonna fiddle with it at home

**Comment by dsheiko** [comment]
chmod added and fixed the path to runner. Now it works to me.
Now I wonder why do have so huge home dir size...
Well, here what I do:
1) create directory for test app ~/Sandbox
2) extract there package from ../example/server/releases
3) iterate version: `npm version patch`
4) edit version in server manifest
5) start up the demo app from ~/Sandbox

my execDir is  "/Users/sheiko/Sandbox/"
so it gets to "/Users/sheiko/Sandbox.bak/" and that is how intended

Can you check in DevTools what it gives you?:
```
require( "path" ).dirname( process.execPath.match(/^([^\0]+?\.app)\//)[1] )
```

**Comment by dsheiko** [comment]
Maybe I have to escape spaces in the path that pass to swap.sh...

**Comment by dsheiko** [comment]
Well, just pushed fixes. Does it work for you now?

**Comment by cry0m1** [comment]
Hi,

1. Tested `git://github.com/dsheiko/nw-autoupdater.git#777e4cf76cdc428820f3ed5ae84a309070828642` within `strategy: "ScriptSwap"` on fresh setup - upgrade works fine on Macos. But I still did not understand how to prevent app's parent folder backup process on MacOS, but do *.app backup itself? Seems readme.md contains text overhead and hardly understandable. As well why `swap.sh` has a duplicate in tmp folder `/var/folders/..................../T/nw-autoupdater` and in original app's path after swap?

2. Repeated test fails as before:
```
Error: Cannot unpack .tar.gz package /var/folders/64/sthbgckj4xgbsd_t11pfxpjc0000gn/T/mac-x64.tar.gz
    at AutoUpdater.unpack (/Users/%USERNAME%/node_modules/nw-autoupdater/index.js:126:19)
    at <anonymous>
```
```
$ pwd &&  find ./ -name "*x64*"
/var/folders/64/sthbgckj4xgbsd_t11pfxpjc0000gn/T
.//mac-x64.tar.gz
```

Debugging shows:
```
index.html:64 Error: Error: EEXIST: file already exists, symlink 'Versions/Current/Helpers' -> '/var/folders/64/sthbgckj4xgbsd_t11pfxpjc0000gn/T/nw-autoupdater/%APPNAME%.app/Contents/Versions/58.0.3029.81/nwjs Framework.framework/Helpers'
    at AutoUpdater.unpack (/Users/%USERNAME%/node_modules/nw-autoupdater/index.js:127:27)
    at <anonymous>
```
I checked folder described above:
```
$ pwd && \ls -la nw-autoupdater/
/var/folders/64/sthbgckj4xgbsd_t11pfxpjc0000gn/T
total 8
drwxr-xr-x@   4 %USERNAME%  staff   136 Apr 26 15:13 .
drwx------@ 101 %USERNAME%  staff  3434 Apr 26 15:14 ..
drwxr-xr-x@   3 %USERNAME%  staff   102 Apr 26 14:30 %APPNAME%.app
-rwxrwxrwx@   1 %USERNAME%  staff   661 Apr 26 15:13 swap.sh
```

Seems script have to delete its tmp folder `nw-autoupdater` in `/var/folders/64/.................../T` after success swap.

3. Did not test on other systems, needed to fix macos firstly.

**Comment by dsheiko** [comment]
In fact Beta is not actual anymore, so I close the issue. Let's set new ones for the master branch
